services:
  going2test-web:
    container_name: going2test-web
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    tty: true
    ports:
      - 3001:3000
    networks:
      - going2test_network
    volumes:
      - ../../.:/usr/app/
    env_file: ../../.env
    entrypoint: wait-for going2test-api:3000 -t 40 -- npm run install-n-run

networks:
  going2test_network:
    name: going2test_network
    external: true
